/** A template file as stored: text with placeholders, or base64 for binary files. */
export interface TemplateFile {
  readonly path: string
  readonly text?: string
  readonly base64?: string
  readonly executable?: boolean
}

const textOrNone = (bytes: Uint8Array): string | undefined => {
  if (bytes.includes(0)) return undefined
  try {
    return new TextDecoder("utf-8", { fatal: true }).decode(bytes)
  } catch {
    return undefined
  }
}

/** The generated module for a template's files. */
export const embed = (files: ReadonlyArray<{ readonly path: string; readonly bytes: Uint8Array; readonly executable: boolean }>): string => {
  const entries: TemplateFile[] = files.map((f) => {
    const text = textOrNone(f.bytes)
    return {
      path: f.path,
      ...(text !== undefined ? { text } : { base64: Buffer.from(f.bytes).toString("base64") }),
      ...(f.executable ? { executable: true } : {}),
    }
  })
  return `// Generated by scripts/generate.ts from the template directory. Don't edit.\nimport type { TemplateFile } from "../embed.ts"\n\nexport const FILES: ReadonlyArray<TemplateFile> = ${JSON.stringify(entries, null, 2)}\n`
}
