// What a connector produces: files to write, either whole or as a block
// between markers inside an existing file, so reruns replace only their part.

export interface GeneratedFile {
  readonly path: string
  readonly content: string
  /** `block`: merged between BEGIN/END markers into whatever the file already holds. */
  readonly mode: "replace" | "block"
  readonly executable?: boolean
}

const markers = (path: string) => {
  const comment = path.endsWith(".md") ? ["<!-- ", " -->"] : ["# ", ""]
  return {
    begin: `${comment[0]}BEGIN gauntlet (generated by \`gauntlet connect\`; edits inside are replaced)${comment[1]}`,
    end: `${comment[0]}END gauntlet${comment[1]}`,
  }
}

/** Puts `block` between the markers in `existing`, replacing a previous block, or appends it. */
export const mergeBlock = (path: string, existing: string | undefined, block: string): string => {
  const { begin, end } = markers(path)
  const wrapped = `${begin}\n${block.trimEnd()}\n${end}\n`
  if (existing === undefined || existing.trim() === "") return wrapped
  const start = existing.indexOf(begin)
  const stop = existing.indexOf(end)
  if (start >= 0 && stop > start) return `${existing.slice(0, start)}${wrapped}${existing.slice(stop + end.length).replace(/^\n/, "")}`
  return `${existing.trimEnd()}\n\n${wrapped}`
}

/** The final content of a generated file given what's on disk. */
export const render = (file: GeneratedFile, existing: string | undefined): string =>
  file.mode === "replace" ? file.content : mergeBlock(file.path, existing, file.content)
