#!/bin/sh
# Generated by `gauntlet connect github --mode org`. Creates the org ruleset
# that requires the Gauntlet workflow from your policy repository, pinned to
# its current commit. Run with a token that can administer org rulesets:
#   ./apply-ruleset.sh <org> <policy-repo>
set -eu
org="$1"
repo="$2"
repo_id=$(gh api "repos/$org/$repo" --jq .id)
sha=$(gh api "repos/$org/$repo/commits/HEAD" --jq .sha)
gh api -X POST "orgs/$org/rulesets" --input - <<JSON
{
  "name": "gauntlet",
  "target": "branch",
  "enforcement": "active",
  "conditions": {
    "ref_name": { "include": ["~DEFAULT_BRANCH"], "exclude": [] },
    "repository_name": { "include": ["~ALL"], "exclude": ["$repo"] }
  },
  "rules": [
    { "type": "workflows", "parameters": { "workflows": [ { "path": ".github/workflows/gauntlet.yml", "repository_id": $repo_id, "sha": "$sha" } ] } },
    { "type": "pull_request", "parameters": { "require_code_owner_review": true, "required_approving_review_count": 1, "dismiss_stale_reviews_on_push": true, "require_last_push_approval": true, "required_review_thread_resolution": false } }
  ]
}
JSON
echo "Ruleset created; the workflow is pinned to $sha. Re-run after changing the policy repository's workflow."
