/** The generated module that embeds the example policies. */
export const examplesModule = (examples: ReadonlyArray<{ readonly name: string; readonly text: string }>) =>
  `// Generated by scripts/generate.ts from examples/policies/valid. Don't edit.\n\nexport const EXAMPLES: ReadonlyArray<{ readonly name: string; readonly text: string }> = ${JSON.stringify(examples, null, 2)}\n`
